# -*- coding: utf-8 -*-
"""Atividade 1- python-extensão.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N7bfhoaDdI3n3i-2sjD7rEFGUUqViP1r
"""

#Fazer um programa em que:
#1. Usuário entra com 3 números (x, y e z)
#2. Imprime na tela x + y
#3. Imprime na tela x elevado a z
#4. Imprime a subração x - y - z

x = int(input(' Qual o primeiro número ? '))
y = int(input(' Qual o segundo número ? '))
z = int(input(" Qual o terceiro número ? "))
print('A soma entre x + y é' , x + y) 
print('x elevado a z é' , x ** z)
print('O resultado da subtração dos números é' , x - y - z)