# -*- coding: utf-8 -*-
"""Par, ímpar, postivo, negativo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gsyi_GRVEnjii3Smp1PGlHncRstQDNB4

Faça um Programa que leia 1 número e, em seguida, informe ao usuário se o número é: Par ou ímpar e Positivo ou negativo;
"""

numerodigitado = input(" Digite um número: ")
  
if int(numerodigitado) % 2 == 0 and int(numerodigitado) > 0:
    print(" O número digitado é par e positivo ")

if int(numerodigitado) % 2 == 0 and int(numerodigitado) < 0:
    print(" O número digitado é par e negativo ")

if int(numerodigitado) % 2 != 0 and int(numerodigitado) > 0:
    print(" O número digitado é ímpar e positivo ")
    
if int(numerodigitado) % 2 !=0 and int(numerodigitado) < 0:
    print( " O número digitado é impar e negativo ")