# -*- coding: utf-8 -*-
"""Programa palavra.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EG3l92YlStEXMuaPfjfUTNDnCkmGnIjm

Fiz de um jeitinho diferente mas, funcionou certinho :)
"""

frase_palavra = input("Digite uma palavra ou frase: ")
for letras in frase_palavra:
 print(letras)